import mongoose from "mongoose";
import dotenv from "dotenv";
import Mood from "./models/mood.js";

dotenv.config();

// Connect to MongoDB
mongoose
  .connect(process.env.MONGO_URI)
  .then(() => console.log("MongoDB Connected"))
  .catch((err) => console.log("DB Connection Error:", err));

// Dummy data array
const dummyMoods = [
{
  userId: "testuser001",
  mood: "happy",
  note: "Morning jog and meditation",
  sleepLevel: 8,
  anxietyLevel: 2,
  energyLevel: 9,
  motivationLevel: 8,
  socialInteraction: 7,
  stressLevel: 2,
  focusLevel: 8,
  tags: ["exercise", "meditation"],
},
{
  userId: "testuser001",
  mood: "happy",
  note: "Productive coding day",
  sleepLevel: 7,
  anxietyLevel: 2,
  energyLevel: 8,
  motivationLevel: 9,
  socialInteraction: 5,
  stressLevel: 3,
  focusLevel: 9,
  tags: ["coding", "work"],
},
{
  userId: "testuser001",
  mood: "okay",
  note: "Busy day at work",
  sleepLevel: 6,
  anxietyLevel: 4,
  energyLevel: 6,
  motivationLevel: 6,
  socialInteraction: 4,
  stressLevel: 5,
  focusLevel: 6,
  tags: ["work"],
},
{
  userId: "testuser001",
  mood: "sad",
  note: "Didn't sleep well",
  sleepLevel: 3,
  anxietyLevel: 6,
  energyLevel: 3,
  motivationLevel: 2,
  socialInteraction: 2,
  stressLevel: 7,
  focusLevel: 3,
  tags: ["sleep"],
},
{
  userId: "testuser001",
  mood: "neutral",
  note: "Regular day",
  sleepLevel: 6,
  anxietyLevel: 3,
  energyLevel: 6,
  motivationLevel: 5,
  socialInteraction: 5,
  stressLevel: 4,
  focusLevel: 6,
  tags: ["routine"],
},
{
  userId: "testuser001",
  mood: "happy",
  note: "Gym workout",
  sleepLevel: 7,
  anxietyLevel: 2,
  energyLevel: 9,
  motivationLevel: 8,
  socialInteraction: 6,
  stressLevel: 2,
  focusLevel: 8,
  tags: ["exercise"],
},
{
  userId: "testuser001",
  mood: "sad",
  note: "Too much workload",
  sleepLevel: 5,
  anxietyLevel: 7,
  energyLevel: 4,
  motivationLevel: 3,
  socialInteraction: 3,
  stressLevel: 8,
  focusLevel: 4,
  tags: ["work", "stress"],
},
{
  userId: "testuser001",
  mood: "okay",
  note: "Met friends",
  sleepLevel: 6,
  anxietyLevel: 3,
  energyLevel: 6,
  motivationLevel: 6,
  socialInteraction: 8,
  stressLevel: 3,
  focusLevel: 6,
  tags: ["friends", "social"],
},
{
  userId: "testuser001",
  mood: "happy",
  note: "Meditation session",
  sleepLevel: 8,
  anxietyLevel: 1,
  energyLevel: 8,
  motivationLevel: 7,
  socialInteraction: 5,
  stressLevel: 1,
  focusLevel: 8,
  tags: ["meditation"],
},
{
  userId: "testuser001",
  mood: "neutral",
  note: "Chill day",
  sleepLevel: 7,
  anxietyLevel: 3,
  energyLevel: 6,
  motivationLevel: 5,
  socialInteraction: 4,
  stressLevel: 3,
  focusLevel: 6,
  tags: ["relax"],
},
{
  userId: "testuser001",
  mood: "sad",
  note: "Argument with friend",
  sleepLevel: 5,
  anxietyLevel: 6,
  energyLevel: 4,
  motivationLevel: 3,
  socialInteraction: 2,
  stressLevel: 7,
  focusLevel: 4,
  tags: ["social"],
},
{
  userId: "testuser001",
  mood: "happy",
  note: "Completed project milestone",
  sleepLevel: 7,
  anxietyLevel: 2,
  energyLevel: 9,
  motivationLevel: 9,
  socialInteraction: 6,
  stressLevel: 3,
  focusLevel: 9,
  tags: ["achievement"],
},
{
  userId: "testuser001",
  mood: "okay",
  note: "Normal office routine",
  sleepLevel: 6,
  anxietyLevel: 4,
  energyLevel: 5,
  motivationLevel: 6,
  socialInteraction: 4,
  stressLevel: 5,
  focusLevel: 5,
  tags: ["routine"],
},
{
  userId: "testuser001",
  mood: "neutral",
  note: "Watched movies",
  sleepLevel: 7,
  anxietyLevel: 2,
  energyLevel: 6,
  motivationLevel: 4,
  socialInteraction: 3,
  stressLevel: 2,
  focusLevel: 5,
  tags: ["relax"],
},
{
  userId: "testuser001",
  mood: "happy",
  note: "Great workout session",
  sleepLevel: 8,
  anxietyLevel: 1,
  energyLevel: 9,
  motivationLevel: 8,
  socialInteraction: 6,
  stressLevel: 1,
  focusLevel: 8,
  tags: ["exercise"],
},
{
  userId: "testuser001",
  mood: "sad",
  note: "Felt overwhelmed",
  sleepLevel: 4,
  anxietyLevel: 7,
  energyLevel: 3,
  motivationLevel: 2,
  socialInteraction: 2,
  stressLevel: 8,
  focusLevel: 3,
  tags: ["stress"],
},
{
  userId: "testuser001",
  mood: "okay",
  note: "Study session",
  sleepLevel: 6,
  anxietyLevel: 3,
  energyLevel: 6,
  motivationLevel: 7,
  socialInteraction: 3,
  stressLevel: 4,
  focusLevel: 8,
  tags: ["study"],
},
{
  userId: "testuser001",
  mood: "happy",
  note: "Weekend trip",
  sleepLevel: 8,
  anxietyLevel: 2,
  energyLevel: 9,
  motivationLevel: 8,
  socialInteraction: 9,
  stressLevel: 2,
  focusLevel: 7,
  tags: ["travel"],
},
{
    userId: "testuser001",
    mood: "happy",
    moodScore: 8,
    sleepLevel: 8,
    anxietyLevel: 2,
    energyLevel: 9,
    motivationLevel: 8,
    socialInteraction: 7,
    createdAt: new Date(),
  },
  {
    userId: "testuser001",
    mood: "okay",
    moodScore: 5,
    sleepLevel: 6,
    anxietyLevel: 4,
    energyLevel: 6,
    motivationLevel: 6,
    socialInteraction: 5,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 1)), // yesterday
  },
  {
    userId: "testuser001",
    mood: "sad",
    moodScore: 3,
    sleepLevel: 4,
    anxietyLevel: 6,
    energyLevel: 3,
    motivationLevel: 3,
    socialInteraction: 2,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 2)), // 2 days ago
  }


];

// Insert data
const insertDummyData = async () => {
  try {
    await Mood.deleteMany({ userId: "testuser001" }); // optional: clear previous dummy data
    const created = await Mood.insertMany(dummyMoods);
    console.log(`Inserted ${created.length} dummy mood entries`);
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

insertDummyData();