export const moodFixActivities = [
  {
    id: "box-breathing",
    title: "Box Breathing Exercise",
    duration: "4 min",
    difficulty: "Easy",
    focusTag: "Anxious",
    benefit: "Anxiety Relief",
    description: "Inhale 4s, hold 4s, exhale 4s, hold 4s.",
    benefits: ["Reduce anxiety", "Lower heart rate", "Improve focus"],
    moods: ["terrible", "sad", "okay", "good", "great"],
    steps: [
      "Sit comfortably and relax your shoulders.",
      "Inhale slowly through your nose for 4 seconds.",
      "Hold your breath for 4 seconds.",
      "Exhale gently for 4 seconds.",
      "Hold again for 4 seconds, then repeat 4 cycles.",
    ],
  },
  {
    id: "478-breathing",
    title: "4-7-8 Relaxation Breathing",
    duration: "4 min",
    difficulty: "Easy",
    focusTag: "Stressed",
    benefit: "Stress Relief",
    description: "Breathe in 4s, hold for 7s, exhale for 8s.",
    benefits: ["Relax nervous system", "Calm racing thoughts", "Improve emotional control"],
    moods: ["terrible", "sad", "okay"],
    steps: [
      "Place one hand on your chest and one on your abdomen.",
      "Inhale quietly through your nose for 4 seconds.",
      "Hold your breath for 7 seconds.",
      "Exhale fully through your mouth for 8 seconds.",
      "Repeat for 4 rounds and notice your body calming.",
    ],
  },
  {
    id: "progressive-muscle",
    title: "Progressive Muscle Relaxation",
    duration: "10 min",
    difficulty: "Medium",
    focusTag: "Stressed",
    benefit: "Body Calm",
    description: "Tense and release each muscle group systematically.",
    benefits: ["Release muscle tension", "Reduce stress signals", "Improve body awareness"],
    moods: ["terrible", "sad", "okay"],
    steps: [
      "Start from your feet and tense muscles for 5 seconds.",
      "Release and feel the tension melt for 10 seconds.",
      "Move upward: calves, thighs, abdomen, shoulders, jaw.",
      "Breathe slowly while releasing each area.",
      "Finish by scanning your body for remaining tension.",
    ],
  },
  {
    id: "grounding-54321",
    title: "5-4-3-2-1 Grounding",
    duration: "5 min",
    difficulty: "Easy",
    focusTag: "Anxious",
    benefit: "Reduce Overwhelm",
    description: "Use your senses to reconnect with the present moment.",
    benefits: ["Reduce overwhelm", "Increase present-moment awareness", "Stabilize emotions"],
    moods: ["terrible", "sad"],
    steps: [
      "Name 5 things you can see around you.",
      "Name 4 things you can touch.",
      "Name 3 things you can hear.",
      "Name 2 things you can smell.",
      "Name 1 thing you can taste or appreciate now.",
    ],
  },
  {
    id: "gentle-walk",
    title: "Gentle Walk Reset",
    duration: "10 min",
    difficulty: "Easy",
    focusTag: "Stressed",
    benefit: "Energy Boost",
    description: "A short mindful walk to refresh mood and focus.",
    benefits: ["Increase energy", "Clear mental fog", "Improve mood naturally"],
    moods: ["sad", "okay", "good"],
    steps: [
      "Walk at a comfortable pace for 10 minutes.",
      "Keep your breathing steady and natural.",
      "Notice one pleasant detail in your environment.",
      "Relax your jaw and shoulders while walking.",
      "Finish with one positive intention for the rest of the day.",
    ],
  },
  {
    id: "gratitude-note",
    title: "Gratitude Note",
    duration: "6 min",
    difficulty: "Easy",
    focusTag: "Sad",
    benefit: "Positive Reframe",
    description: "Write 3 small things that felt okay or good today.",
    benefits: ["Shift focus to positives", "Build emotional resilience", "Support hopeful thinking"],
    moods: ["okay", "good", "great"],
    steps: [
      "Open a note or journal page.",
      "Write 3 specific moments you are grateful for.",
      "For each, write why it mattered to you.",
      "Read them once slowly.",
      "Save this note for hard days.",
    ],
  },
  {
    id: "social-checkin",
    title: "Social Check-in",
    duration: "5 min",
    difficulty: "Easy",
    focusTag: "Sad",
    benefit: "Connection Support",
    description: "Send a short message to someone you trust.",
    benefits: ["Reduce isolation", "Strengthen support system", "Improve emotional safety"],
    moods: ["sad", "okay", "good"],
    steps: [
      "Choose one trusted person.",
      "Send a short honest message about your day.",
      "Ask one simple question to invite connection.",
      "Take 3 deep breaths while waiting.",
      "Acknowledge yourself for reaching out.",
    ],
  },
  {
    id: "focus-sprint",
    title: "Focus Sprint",
    duration: "15 min",
    difficulty: "Medium",
    focusTag: "Happy",
    benefit: "Task Clarity",
    description: "One short focus block with no distractions.",
    benefits: ["Improve productivity", "Reduce mental clutter", "Build confidence through progress"],
    moods: ["okay", "good", "great"],
    steps: [
      "Pick one small task only.",
      "Set a 15-minute timer.",
      "Silence notifications and keep one tab/app open.",
      "Work until the timer ends.",
      "Mark progress and reward yourself with a short break.",
    ],
  },
];
